minor fixes to run

diff --git a/run b/run
--- a/run
+++ b/run
@@ -34,10 +34,12 @@ while [[ $# -gt 0 ]]; do
   esac
 done
 
-trap 'rm $INPUT_FILE;rm $OUTPUT_FILE;kill $COPROC_PID' EXIT
+trap 'rm $INPUT_FILE;rm $OUTPUT_FILE;kill $COPROC_PID 2>/dev/null' EXIT
 coproc forge script --ffi --sender $ETH_FROM ${OPTIONS[*]} $NAME 1>&2
 
 if ps -p $COPROC_PID > /dev/null; then
+  # WARNING: this hangs if the script fails
+  # Need to ^C to exit
   read IN <$OUTPUT_FILE 
 
   if [[ ${#ARGS[@]} -eq 0 ]]; then
